import "@/app/globals.css";
import SupabaseProvider from "@/app/supabase-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black">
        <SupabaseProvider>{children}</SupabaseProvider>
      </body>
    </html>
  );
}
